name: Deploy backend

on: workflow_call

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Build backend
        run: echo Собирается билд бекенда (прогоняются юнит тесты при сборке), формируется и публикуется докер образ с изменениями
  
  deploy-stage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend to stage/review app
        run: echo происходит деплой бэкенда
