name: Deploy to production

on: workflow_call

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy beckend to production
        run: echo Происходит деплой бэкенда
  
  deploy-stage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend to production
        run: echo происходит деплой фронтенда
