name: Deploy frontend

on: workflow_call

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Build frontend
        run: echo Собирается билд фронтенда (прогоняются юнит тесты при сборке), формируется и публикуется докер образ с изменениями
  
  deploy-stage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend to stage/review app
        run: echo происходит деплой фронтенда
